# Generated by Django 6.0.4 on 2026-04-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('study', 'دراسة 📚'), ('work', 'عمل 💼'), ('health', 'صحة 🍏'), ('other', 'أخرى ⚙️')], max_length=20)),
                ('due_date', models.DateTimeField()),
                ('progress', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
